### PR TITLE
fix new ubuntu cloud-init. refs https://bugs.launchpad.net/ubuntu/+so…

### PR DESCRIPTION
**Pull request by php53unit**
…urce/cloud-init/+bug/1987691

### Testing done

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by demenevai** [comment]
@radio1983 hi!
Can you explain a little bit what this change do?
Follow the [bugreport link](https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/1987691) I see that discussion in thread is about groups definition, fixed in https://github.com/canonical/cloud-init/commit/ccea0d44
As I can see in cloud init [schema on that commit](https://github.com/canonical/cloud-init/blob/ccea0d44752b86bd9da951708df048be17561545/cloudinit/config/schemas/schema-cloud-config-v1.json#L157) `sudo` definition can be only `false`  or rule definition string.

**Comment by php53unit** [comment]
sudo now boolean and can only be "true" of "false"

**Comment by demenevai** [comment]
@php53unit 
The [latest schema](https://github.com/canonical/cloud-init/blob/aeafb83c78c619d8d333ccac498adec07d239df9/cloudinit/config/schemas/schema-cloud-config-v1.json#L398) is `string` | `null` and from 22.2 version it will show deprecation warning, if I understand schema correct.

**Comment by php53unit** [comment]
Yes, pull request must be rejected, thanks!

**Pull request closed without merging**
